name: generate-reports
concurrency: generate-reports

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  run-ghrs-with-matrix:
    name: generate-reports
    runs-on: ubuntu-latest
    strategy:
      matrix:
        statsRepo: ['varabyte/kobweb-templates', 'varabyte/kobweb', 'varabyte/kotter', 'varabyte/truthish']

      fail-fast: false
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: ${{ matrix.statsRepo }}
          ghtoken: ${{ secrets.ghrs_github_api_token }}
          databranch: main
